services:
  db:
    image: postgres:16-alpine
    container_name: sphere-db
    restart: always
    env_file:
      - ./sphere-backend/.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: sphere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./sphere-backend
    container_name: sphere-api
    depends_on:
      - db
    env_file:
      - ./sphere-backend/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sphere
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "8080:8080"
  
  frontend: 
    build: ./sphere-frontend
    container_name: sphere_ui
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data: